name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Restore ccache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ccache
          key: ${{ matrix.os }}-ccache-${{ github.sha }}
          restore-keys: ${{ matrix.os }}-ccache-

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake libudev-dev libspdlog-dev ccache

      - name: Configure
        run: cmake -B build -DCMAKE_PREFIX_PATH=/usr -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

      - name: Build
        run: cmake --build build

      - name: Install
        run: cmake --install build --prefix install

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-binaries
          path: install/bin/*
